fixes regression introduced by 643bdd9 - QuitBacktraceTweaker eats everything
The commit message for 643bdd9 states "trust the load path (more to do,
but good start)", but the chunk undone by this commit was changed in
error: instead of having it use load_path to locate the rspec lib files
to add to the ignore, it used the current working directory instead (big
difference!).  This effectively caused the working project's lib files
to be removed from the backtrace, instead of the rspec gem files :)

[#912 state:resolved milestone:1.3.1]